"""Section management routes."""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
import logging

from app.db.session import get_db
from app.services.section_service import section_service
from app.services.question_card_service import question_card_service
from app.services.s3_service import s3_service
from app.schemas.section import SectionResponse
from app.schemas.question_card import QuestionCardSchema

logger = logging.getLogger(__name__)

router = APIRouter()


def browser_safe_file_url(file_url: str | None) -> str | None:
    """Return a browser-accessible URL for private MinIO/S3 objects."""
    if not file_url:
        return None

    try:
        return s3_service.generate_presigned_url(file_url)
    except Exception as exc:
        logger.warning(f"Could not generate presigned URL for {file_url}: {exc}")
        return file_url.replace("http://minio:9000", "http://localhost:9000")


@router.get("/{section_id}", response_model=SectionResponse)
async def get_section(section_id: str, db: Session = Depends(get_db)):
    """Get section by ID with all details."""
    logger.info(f"Retrieving section {section_id}")
    section = section_service.get_section(db, section_id)
    return SectionResponse(
        id=section.id,
        document_id=section.document_id,
        section_number=section.section_number,
        title=section.title,
        extracted_text=section.extracted_text,
        ai_summary=section.ai_summary,
        created_at=section.created_at,
    )


@router.patch("/{section_id}")
async def update_section(section_id: str, db: Session = Depends(get_db)):
    """Update section information."""
    # For MVP, sections are mostly read-only (generated by AI)
    # This can be enhanced later for manual title editing
    raise HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail="Section update not implemented in MVP"
    )


@router.get("/{section_id}/question-cards", response_model=List[QuestionCardSchema])
async def get_section_question_cards(section_id: str, db: Session = Depends(get_db)):
    """Get all question cards for a section, ordered by orderIndex."""
    logger.info(f"Retrieving question cards for section {section_id}")

    # Verify section exists
    section_service.get_section(db, section_id)

    # Get question cards
    cards = question_card_service.get_question_cards_by_section(db, section_id)

    # Convert to schema
    from app.schemas.question_card import (
        CoverageRule, SufficiencyEvidence, CardUI, QuestionCardSchema
    )

    result = []
    for card in cards:
        # Parse coverage rule
        normalized_rule = question_card_service.normalize_coverage_rule_for_important_elements(
            card.coverage_rule
        )
        coverage_rule = CoverageRule(**normalized_rule)

        # Parse evidence if exists
        evidence = None
        if hasattr(card, 'evidence') and card.evidence:
            evidence = SufficiencyEvidence(**card.evidence)

        # Parse UI settings
        ui = None
        if card.ui:
            ui = CardUI(**card.ui)

        result.append(QuestionCardSchema(
            id=card.id,
            documentId=card.document_id,
            sectionId=card.section_id,
            sectionNumber=card.section_number,
            questionText=card.question_text,
            questionType=card.question_type,
            importance=card.importance,
            coverageRule=coverage_rule,
            suggestedFollowup=card.suggested_followup,
            expectedAnswerElements=card.expected_answer_elements or [],
            orderIndex=card.order_index,
            status=card.status,
            confidence=float(card.confidence) if card.confidence else None,
            evidence=evidence,
            ui=ui,
            createdBy=card.created_by,
            createdAt=card.created_at,
            updatedAt=card.updated_at
        ))

    return result
