"""Stakeholder Slot model."""

from datetime import datetime

from sqlalchemy import JSON, Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from app.db.session import Base


class StakeholderSlot(Base):
    """StakeholderSlot model - a role slot in the stakeholder plan.

    Represents a recommended role to interview (e.g. "Engineering/IT"),
    not a specific person. Generated by AI from project scope, or
    created manually by the user.
    """

    __tablename__ = "stakeholder_slots"

    id = Column(String, primary_key=True)
    project_id = Column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )

    role_category = Column(String, nullable=False)
    role_label = Column(String, nullable=False)
    rationale = Column(Text, nullable=True)
    expected_contributions = Column(JSON, nullable=False, default=[])
    key_questions_to_cover = Column(JSON, nullable=False, default=[])
    priority = Column(String, nullable=False, default="required")
    min_interviews = Column(Integer, nullable=False, default=1)
    first_wave = Column(Boolean, nullable=False, default=False)
    status = Column(String, nullable=False, default="unassigned")
    order_index = Column(Integer, nullable=False, default=0)
    source = Column(String, nullable=False, default="ai_suggested")

    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="stakeholder_slots")
    profile_assignments = relationship(
        "StakeholderProfileSlot",
        back_populates="slot",
        cascade="all, delete-orphan",
    )
