"""Chinese text normalization helpers."""

from __future__ import annotations

from typing import Any

try:  # pragma: no cover - optional runtime dependency
    from opencc import OpenCC
except Exception:  # pragma: no cover - import may fail before dependency install
    OpenCC = None  # type: ignore[assignment]


_OPENCC = OpenCC("s2twp") if OpenCC else None

# Small fallback map for environments that have not installed OpenCC yet.
# This is intentionally conservative; production installs should use OpenCC.
_COMMON_SIMPLIFIED_TO_TRADITIONAL = str.maketrans(
    {
        "个": "個",
        "为": "為",
        "与": "與",
        "业": "業",
        "东": "東",
        "两": "兩",
        "并": "並",
        "临": "臨",
        "举": "舉",
        "义": "義",
        "习": "習",
        "书": "書",
        "买": "買",
        "乱": "亂",
        "争": "爭",
        "于": "於",
        "亏": "虧",
        "云": "雲",
        "亚": "亞",
        "产": "產",
        "处": "處",
        "亲": "親",
        "亿": "億",
        "仅": "僅",
        "从": "從",
        "仓": "倉",
        "们": "們",
        "优": "優",
        "会": "會",
        "传": "傳",
        "伤": "傷",
        "体": "體",
        "余": "餘",
        "佣": "傭",
        "侠": "俠",
        "侧": "側",
        "侦": "偵",
        "侣": "侶",
        "侥": "僥",
        "侨": "僑",
        "侩": "儈",
        "侪": "儕",
        "侬": "儂",
        "俣": "俁",
        "俦": "儔",
        "俨": "儼",
        "俩": "倆",
        "俪": "儷",
        "俭": "儉",
        "债": "債",
        "倾": "傾",
        "偬": "傯",
        "偿": "償",
        "儿": "兒",
        "兑": "兌",
        "党": "黨",
        "兰": "蘭",
        "关": "關",
        "兴": "興",
        "养": "養",
        "兽": "獸",
        "内": "內",
        "冈": "岡",
        "册": "冊",
        "写": "寫",
        "军": "軍",
        "农": "農",
        "冲": "衝",
        "决": "決",
        "况": "況",
        "冻": "凍",
        "净": "淨",
        "准": "準",
        "几": "幾",
        "凤": "鳳",
        "凭": "憑",
        "凯": "凱",
        "击": "擊",
        "凿": "鑿",
        "刘": "劉",
        "则": "則",
        "刚": "剛",
        "创": "創",
        "删": "刪",
        "别": "別",
        "剂": "劑",
        "剐": "剮",
        "剑": "劍",
        "剧": "劇",
        "剩": "剩",
        "动": "動",
        "务": "務",
        "劝": "勸",
        "办": "辦",
        "务": "務",
        "励": "勵",
        "劳": "勞",
        "势": "勢",
        "勋": "勳",
        "区": "區",
        "医": "醫",
        "华": "華",
        "协": "協",
        "单": "單",
        "卖": "賣",
        "卢": "盧",
        "卫": "衛",
        "却": "卻",
        "厂": "廠",
        "历": "歷",
        "厉": "厲",
        "压": "壓",
        "厌": "厭",
        "县": "縣",
        "参": "參",
        "双": "雙",
        "发": "發",
        "变": "變",
        "叙": "敘",
        "叶": "葉",
        "号": "號",
        "叹": "嘆",
        "叽": "嘰",
        "吁": "籲",
        "后": "後",
        "吗": "嗎",
        "启": "啟",
        "吴": "吳",
        "员": "員",
        "呗": "唄",
        "呜": "嗚",
        "咏": "詠",
        "咙": "嚨",
        "咛": "嚀",
        "咝": "噝",
        "响": "響",
        "哑": "啞",
        "哒": "噠",
        "哗": "嘩",
        "哟": "喲",
        "唤": "喚",
        "唬": "唬",
        "啧": "嘖",
        "啬": "嗇",
        "啭": "囀",
        "问": "問",
        "间": "間",
        "闸": "閘",
        "闹": "鬧",
        "闻": "聞",
        "队": "隊",
        "阳": "陽",
        "阴": "陰",
        "阵": "陣",
        "阶": "階",
        "际": "際",
        "陆": "陸",
        "陈": "陳",
        "陕": "陝",
        "险": "險",
        "随": "隨",
        "隐": "隱",
        "难": "難",
        "页": "頁",
        "户": "戶",
        "顶": "頂",
        "项": "項",
        "顺": "順",
        "须": "須",
        "预": "預",
        "领": "領",
        "频": "頻",
        "题": "題",
        "颜": "顏",
        "额": "額",
        "风": "風",
        "飞": "飛",
        "饭": "飯",
        "馆": "館",
        "马": "馬",
        "验": "驗",
        "体": "體",
        "挂": "掛",
        "号": "號",
        "线": "線",
        "约": "約",
        "当": "當",
        "务": "務",
        "员": "員",
        "现": "現",
        "场": "場",
        "资": "資",
        "讯": "訊",
        "录": "錄",
        "转": "轉",
        "输": "輸",
        "统": "統",
        "设": "設",
        "计": "計",
        "医": "醫",
        "疗": "療",
        "柜": "櫃",
        "台": "台",
        "项": "項",
        "确": "確",
        "认": "認",
        "点": "點",
    }
)


def to_traditional_zh(value: str | None) -> str:
    """Normalize Chinese text to Traditional Chinese.

    OpenAI transcription can return Simplified Chinese when only `language=zh`
    is specified.  Prefer OpenCC when installed; keep a conservative fallback so
    the app still behaves sensibly in local dev before dependencies are updated.
    """
    text = (value or "").strip()
    if not text:
        return ""
    if _OPENCC:
        text = _OPENCC.convert(text).strip()
    else:
        text = text.translate(_COMMON_SIMPLIFIED_TO_TRADITIONAL).strip()
    return text.replace("櫃台", "櫃檯")


def normalize_traditional_zh(value: Any) -> Any:
    """Recursively normalize strings inside JSON-like values to Traditional Chinese."""
    if isinstance(value, str):
        return to_traditional_zh(value)
    if isinstance(value, list):
        return [normalize_traditional_zh(item) for item in value]
    if isinstance(value, dict):
        return {key: normalize_traditional_zh(item) for key, item in value.items()}
    return value
