/**
 * Question Card API functions for InsightGuide
 */

import apiClient from './client'
import type {
  CardImportance,
  CoverageRule,
  QuestionCard,
  QuestionType,
} from '@/types/questionCard'

// Simplified form data - user edits question text, followup, and importance
export interface QuestionCardFormData {
  sectionId: string
  questionText: string
  suggestedFollowup: string
  importance: CardImportance // User selects: 'must' or 'should'
  // Internal fields for compatibility (will be auto-generated by AI)
  questionType?: QuestionType
  semanticAnchors?: string
  expectedKeywords?: string
  mustMentionElements?: string
  expectedAnswerElements?: string[]
  coverageRule?: CoverageRule
  estimatedSeconds?: number
}

function lines(value: string) {
  return value
    .split('\n')
    .map((item) => item.trim())
    .filter(Boolean)
}

function toPayload(form: QuestionCardFormData) {
  const coverageRule = form.semanticAnchors
    ? {
        semanticAnchors: lines(form.semanticAnchors),
        expectedKeywords: lines(form.expectedKeywords || ''),
        mustMentionElements: lines(form.mustMentionElements || '').map((text) => ({
          text,
          required: true,
          aliases: [],
          subpoints: [],
        })),
        negativeSignals: [],
        thresholds: {
          probablySufficient: 0.62,
          sufficient: 0.78,
        },
        scoringWeights: {
          semanticSimilarity: 0.55,
          keywordCoverage: 0.25,
          elementCoverage: 0.2,
        },
      }
    : form.coverageRule

  // Simplified payload - user provides question text, followup, and importance
  // AI will generate other fields
  return {
    sectionId: form.sectionId,
    questionText: form.questionText,
    suggestedFollowup: form.suggestedFollowup,
    importance: form.importance, // User-selected importance
    // Only include optional fields if they exist (for backwards compatibility)
    ...(form.questionType && { questionType: form.questionType }),
    ...(form.expectedAnswerElements && { expectedAnswerElements: form.expectedAnswerElements }),
    ...(form.estimatedSeconds && { estimatedSeconds: form.estimatedSeconds }),
    ...(coverageRule && { coverageRule }),
  }
}

export function cardToForm(card: QuestionCard): QuestionCardFormData {
  // Simplified form - extract question text, followup, and importance for user editing
  return {
    sectionId: card.sectionId,
    questionText: card.questionText,
    suggestedFollowup: card.suggestedFollowup ?? '',
    importance: card.importance, // User can edit importance
    // Keep internal rules intact while the simplified editor only exposes question/followup/importance.
    questionType: card.questionType,
    expectedAnswerElements: card.expectedAnswerElements,
    coverageRule: card.coverageRule,
    estimatedSeconds: 0, // Default value
  }
}

export const questionCardsAPI = {
  async getDocumentCards(documentId: string): Promise<QuestionCard[]> {
    const response = await apiClient.get(`/api/question-cards/document/${documentId}`)
    return response.data
  },

  async getCard(cardId: string): Promise<QuestionCard> {
    const response = await apiClient.get(`/api/question-cards/${cardId}`)
    return response.data
  },

  async createCard(form: QuestionCardFormData): Promise<QuestionCard> {
    const response = await apiClient.post('/api/question-cards/', toPayload(form))
    return response.data
  },

  async updateCard(cardId: string, form: QuestionCardFormData): Promise<QuestionCard> {
    const response = await apiClient.patch(`/api/question-cards/${cardId}`, toPayload(form))
    return response.data
  },

  async cleanupFollowup(text: string): Promise<string> {
    const response = await apiClient.post('/api/question-cards/followup/cleanup', { text })
    return response.data.cleanedText
  },

  async regenerateFollowup(cardId: string): Promise<QuestionCard> {
    const response = await apiClient.post(`/api/question-cards/${cardId}/followup/regenerate`)
    return response.data
  },

  async deleteCard(cardId: string): Promise<void> {
    await apiClient.delete(`/api/question-cards/${cardId}`)
  },

  async reorderSectionCards(sectionId: string, cardIds: string[]): Promise<QuestionCard[]> {
    const response = await apiClient.patch(
      `/api/question-cards/sections/${sectionId}/reorder`,
      cardIds
    )
    return response.data
  },
}
