"""Prompt seed data — INITIAL VALUES ONLY.

This file provides default prompts for first-time database seeding.
After seeding, the database is the single source of truth.
All prompt edits should happen through the Dashboard (Prompt 管理中心).
This file is NOT used at runtime — only during seed_template() when a template doesn't exist yet.
"""

PROMPT_SEEDS = [
    {
        "key": "generate_interview_themes",
        "name": "訪談主題生成",
        "category": "document_analysis",
        "description": "Phase 1: 從 BRD 初稿產生訪談單元計畫",
        "model": "gpt-4o",
        "risk_level": "high",
        "service_file": "openai_service.py",
        "service_function": "generate_interview_themes()",
        "input_variables": ["document_title", "section_list", "full_text"],
        "output_format": "JSON: interview_objective, themes[], priority_order",
        "system_prompt": "你是一位資深的商業分析師（BA），擅長從需求初稿中找出資訊缺口，並設計訪談策略。",
        "user_prompt_template": None,
    },
    {
        "key": "generate_theme_question_cards",
        "name": "訪談問題卡生成",
        "category": "document_analysis",
        "description": "Phase 2: 為每個訪談單元產生提問主題與建議提問",
        "model": "gpt-4o",
        "risk_level": "high",
        "service_file": "openai_service.py",
        "service_function": "generate_theme_question_cards()",
        "input_variables": ["document_title", "document_summary", "theme_title", "theme_rationale", "theme_brd_mapping", "source_sections_text"],
        "output_format": "JSON: cards[] with focus_text, question_text, coverage_rule",
        "system_prompt": "你是一位資深商業分析師，負責為特定訪談單元設計「提問主題」與「建議提問」。",
        "user_prompt_template": None,
    },
    {
        "key": "classify_speaker",
        "name": "說話者角色分類",
        "category": "interview_realtime",
        "description": "即時判斷語音屬於訪問者或受訪者",
        "model": "gpt-5.4-mini",
        "risk_level": "low",
        "service_file": "openai_service.py",
        "service_function": "classify_speaker()",
        "input_variables": ["transcript"],
        "output_format": "Single word: interviewer | interviewee",
        "system_prompt": "判斷以下對話片段是訪問者還是受訪者說的。只回覆 'interviewer' 或 'interviewee'。",
        "user_prompt_template": None,
    },
    {
        "key": "interviewer_card_semantic_match",
        "name": "訪問者提問-問題卡匹配",
        "category": "interview_realtime",
        "description": "語義比對訪問者發言與問題卡，決定啟動哪張卡",
        "model": "gpt-5.4-mini",
        "risk_level": "high",
        "service_file": "answer_evaluation_engine.py",
        "service_function": "_semantic_interviewer_card_match()",
        "input_variables": ["utterance_text", "card_lines"],
        "output_format": "JSON: card_id, confidence, reason",
        "system_prompt": "你是訪談問題卡語意匹配器。只回傳 JSON，不要輸出額外文字。",
        "user_prompt_template": None,
    },
    {
        "key": "answer_sufficiency_batch",
        "name": "回答充分度批次評估",
        "category": "interview_realtime",
        "description": "批次評估受訪者回答是否充分回應所有候選問題卡",
        "model": "gpt-5.4-mini",
        "risk_level": "high",
        "service_file": "answer_evaluation_engine.py",
        "service_function": "_batch_judge_answer_sufficiency()",
        "input_variables": ["context", "candidate_cards"],
        "output_format": "JSON: cards[] with confidence, is_covered, covered_element_ids, suggested_followup",
        "system_prompt": "你是 BRD 訪談評估系統。判斷受訪者的回答是否充分回應了每個提問重點。",
        "user_prompt_template": None,
    },
    {
        "key": "semantic_coverage_judgment",
        "name": "語義覆蓋度判斷",
        "category": "interview_realtime",
        "description": "即時判斷發言是否從語義層面覆蓋問題卡內容",
        "model": "gpt-5.4-mini",
        "risk_level": "high",
        "service_file": "semantic_judge_service.py",
        "service_function": "judge_coverage()",
        "input_variables": ["utterance_text", "title", "description", "semantic_anchors", "expected_keywords", "must_mention_facts"],
        "output_format": "JSON: is_covered, confidence, reasoning, mentioned_keywords[], missing_aspects[]",
        "system_prompt": "你是需求訪談評估專家，負責判斷受訪者的回答是否從語義層面充分回應了提問重點。",
        "user_prompt_template": None,
    },
    {
        "key": "card_completion_percentage",
        "name": "問題卡完成度評分",
        "category": "interview_realtime",
        "description": "根據累積逐字稿評估問題卡完成百分比",
        "model": "gpt-5.4-mini",
        "risk_level": "high",
        "service_file": "semantic_judge_service.py",
        "service_function": "judge_completion_percentage()",
        "input_variables": ["title", "description", "semantic_anchors", "expected_keywords", "must_mention_facts", "transcript_context"],
        "output_format": "JSON: completion_percentage, confidence, is_complete, covered_aspects[], missing_aspects[]",
        "system_prompt": "你是簡報主題卡片完成度評分器。只根據逐字稿和卡片要求評分，並只回傳 JSON。",
        "user_prompt_template": None,
    },
    {
        "key": "rewrite_brd_section",
        "name": "BRD 段落改寫",
        "category": "brd_generation",
        "description": "將訪談逐字稿改寫成正式 BRD 段落",
        "model": "gpt-5.4-mini",
        "risk_level": "medium",
        "service_file": "brd_generation_service.py",
        "service_function": "_rewrite_sections_with_ai()",
        "input_variables": ["document_title", "chapter", "focusText", "evidence"],
        "output_format": "Free text (markdown paragraph)",
        "system_prompt": "你是專業的商業分析師，負責將訪談逐字稿改寫成正式的 BRD 段落。",
        "user_prompt_template": None,
    },
    {
        "key": "generate_brd_content",
        "name": "BRD 文件生成",
        "category": "brd_generation",
        "description": "從完整訪談資料產生 BRD 高層結構",
        "model": "gpt-5.5",
        "risk_level": "medium",
        "service_file": "brd_generator_service.py",
        "service_function": "_generate_brd_content()",
        "input_variables": ["interview_data"],
        "output_format": "JSON: title, executive_summary, business_objectives[], stakeholders[]",
        "system_prompt": "You are a business analyst generating a Business Requirements Document (BRD) from an interview session.",
        "user_prompt_template": None,
    },
    {
        "key": "extract_requirements",
        "name": "需求萃取",
        "category": "brd_generation",
        "description": "從問答對中萃取功能/非功能需求",
        "model": "gpt-5.5",
        "risk_level": "medium",
        "service_file": "brd_generator_service.py",
        "service_function": "_extract_requirements()",
        "input_variables": ["qa"],
        "output_format": "JSON: requirements[] with title, description, type, priority",
        "system_prompt": "Extract functional and non-functional requirements from this interview question and answer.",
        "user_prompt_template": None,
    },
    {
        "key": "regenerate_followup",
        "name": "追問建議重新生成",
        "category": "question_editing",
        "description": "為回答不充分的問題重新生成追問建議",
        "model": "gpt-5.5",
        "risk_level": "low",
        "service_file": "ai_question_generator.py",
        "service_function": "regenerate_suggested_followup()",
        "input_variables": ["question_text", "expected_answer_elements", "section_context", "current_followup"],
        "output_format": "JSON: suggestedFollowup",
        "system_prompt": "你是一位資深商業分析師，擅長設計追問策略。",
        "user_prompt_template": None,
    },
    {
        "key": "generate_question_fields",
        "name": "問題卡元資料生成",
        "category": "question_editing",
        "description": "為新問題卡生成類型、重要性、覆蓋規則等元資料",
        "model": "gpt-5.5",
        "risk_level": "medium",
        "service_file": "ai_question_generator.py",
        "service_function": "generate_question_fields()",
        "input_variables": ["question_text", "section_context", "document_context"],
        "output_format": "JSON: questionType, importance, expectedAnswerElements[], coverageRule",
        "system_prompt": "你是一位資深商業分析師，擅長從需求文件中找出資訊缺口並設計訪談問題。",
        "user_prompt_template": None,
    },
    {
        "key": "clean_spoken_script",
        "name": "語音文字清理",
        "category": "utilities",
        "description": "清理語音轉文字的幻覺與噪音",
        "model": "gpt-5.4-mini",
        "risk_level": "low",
        "service_file": "semantic_judge_service.py",
        "service_function": "clean_spoken_script()",
        "input_variables": ["raw_text"],
        "output_format": "JSON: cleaned_text",
        "system_prompt": "你是語意匹配專家。清理語音轉文字的輸出，保留原意。",
        "user_prompt_template": None,
    },
]
