"""clean v2 baseline

Revision ID: 0001_clean_v2_baseline
Revises: 
Create Date: 2026-07-16 16:36:29.133744

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_clean_v2_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("brd_scope", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "brd_readiness_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.Column("readiness_score", sa.Float(), nullable=True),
        sa.Column("generation_mode", sa.String(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("ready_chapters", sa.JSON(), nullable=False),
        sa.Column("insufficient_chapters", sa.JSON(), nullable=False),
        sa.Column("unresolved_conflicts", sa.JSON(), nullable=False),
        sa.Column("suggested_next_interviews", sa.JSON(), nullable=False),
        sa.Column("stakeholder_coverage", sa.JSON(), nullable=True),
        sa.Column("total_memos", sa.Integer(), nullable=False),
        sa.Column("total_stakeholders_interviewed", sa.Integer(), nullable=False),
        sa.Column("total_evidence_entries", sa.Integer(), nullable=False),
        sa.Column("validated_requirements", sa.Integer(), nullable=False),
        sa.Column("markdown_content", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brd_readiness_reports_project_id"),
        "brd_readiness_reports",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "requirement_evidence_matrices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("memo_count", sa.Integer(), nullable=False),
        sa.Column("last_memo_id", sa.String(), nullable=True),
        sa.Column("markdown_content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(
        "ix_evidence_matrices_project_id",
        "requirement_evidence_matrices",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "stakeholder_slots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("role_category", sa.String(), nullable=False),
        sa.Column("role_label", sa.String(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("expected_contributions", sa.JSON(), nullable=False),
        sa.Column("key_questions_to_cover", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("min_interviews", sa.Integer(), nullable=False),
        sa.Column("first_wave", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stakeholder_slots_project_id"), "stakeholder_slots", ["project_id"], unique=False
    )
    op.create_table(
        "stakeholder_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role_title", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("stakeholder_type", sa.String(), nullable=False),
        sa.Column("expertise_tags", sa.JSON(), nullable=False),
        sa.Column("knowledge_boundaries", sa.JSON(), nullable=False),
        sa.Column("decision_power", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("interview_count", sa.Integer(), nullable=False),
        sa.Column("last_interviewed_at", sa.DateTime(), nullable=True),
        sa.Column("recommended_by_memo_id", sa.String(), nullable=True),
        sa.Column("recommended_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stakeholder_profiles_project_id"),
        "stakeholder_profiles",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "stakeholder_profile_slots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("slot_id", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("fit_level", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["stakeholder_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["stakeholder_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "slot_id", name="uq_stakeholder_profile_slot"),
    )
    op.create_index(
        op.f("ix_stakeholder_profile_slots_profile_id"),
        "stakeholder_profile_slots",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stakeholder_profile_slots_project_id"),
        "stakeholder_profile_slots",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stakeholder_profile_slots_slot_id"),
        "stakeholder_profile_slots",
        ["slot_id"],
        unique=False,
    )
    op.create_table(
        "interview_series",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("stakeholder_profile_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("topic_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["stakeholder_profile_id"], ["stakeholder_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "stakeholder_profile_id",
            "topic_key",
            name="uq_interview_series_project_profile_topic",
        ),
    )
    op.create_index(
        op.f("ix_interview_series_project_id"), "interview_series", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_series_stakeholder_profile_id"),
        "interview_series",
        ["stakeholder_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_series_status"), "interview_series", ["status"], unique=False
    )
    op.create_table(
        "interview_rounds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("series_id", sa.String(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=True),
        sa.Column("generation_mode", sa.String(), nullable=False),
        sa.Column("source_session_ids", sa.JSON(), nullable=False),
        sa.Column("focus_topics", sa.JSON(), nullable=False),
        sa.Column("exclude_completed_questions", sa.Boolean(), nullable=False),
        sa.Column("guide_document_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guide_document_id"],
            ["documents.id"],
            name="interview_rounds_guide_document_id_fkey",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["interview_series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "round_number", name="uq_interview_round_series_number"),
    )
    op.create_index(
        op.f("ix_interview_rounds_guide_document_id"),
        "interview_rounds",
        ["guide_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_rounds_series_id"), "interview_rounds", ["series_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_rounds_status"), "interview_rounds", ["status"], unique=False
    )
    op.create_table(
        "interview_round_slots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("slot_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["round_id"], ["interview_rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["stakeholder_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_id", "slot_id", name="uq_interview_round_slot"),
    )
    op.create_index(
        op.f("ix_interview_round_slots_round_id"),
        "interview_round_slots",
        ["round_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_round_slots_slot_id"),
        "interview_round_slots",
        ["slot_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("stakeholder_profile_id", sa.String(), nullable=True),
        sa.Column("interview_round_id", sa.String(), nullable=True),
        sa.Column("guide_version", sa.Integer(), nullable=False),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source_file_url", sa.Text(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("interview_objective", sa.Text(), nullable=True),
        sa.Column(
            "interview_priority_order", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("interview_priority_reasoning", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interview_round_id"], ["interview_rounds.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["stakeholder_profile_id"], ["stakeholder_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_interview_round_id"), "documents", ["interview_round_id"], unique=False
    )
    op.create_index(op.f("ix_documents_is_frozen"), "documents", ["is_frozen"], unique=False)
    op.create_index(op.f("ix_documents_project_id"), "documents", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_documents_stakeholder_profile_id"),
        "documents",
        ["stakeholder_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False)
    op.create_table(
        "interview_themes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("theme_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("brd_mapping", sa.ARRAY(sa.String()), server_default="{}", nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_themes_document_id"), "interview_themes", ["document_id"], unique=False
    )
    op.create_table(
        "prep_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prep_sessions_document_id"), "prep_sessions", ["document_id"], unique=True
    )
    op.create_index(op.f("ix_prep_sessions_status"), "prep_sessions", ["status"], unique=False)
    op.create_index(op.f("ix_prep_sessions_user_id"), "prep_sessions", ["user_id"], unique=False)
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("prep_session_id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("stakeholder_profile_id", sa.String(), nullable=True),
        sa.Column("interview_round_id", sa.String(), nullable=True),
        sa.Column("continued_from_session_id", sa.String(), nullable=True),
        sa.Column("interview_objective", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_theme_id", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.Column("paused_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("active_card_id", sa.String(), nullable=True),
        sa.Column("active_card_source", sa.String(), nullable=True),
        sa.Column("active_card_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("pending_answer_buffer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["continued_from_session_id"], ["interview_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["current_theme_id"],
            ["interview_themes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interview_round_id"], ["interview_rounds.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["prep_session_id"],
            ["prep_sessions.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["stakeholder_profile_id"], ["stakeholder_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_sessions_continued_from_session_id"),
        "interview_sessions",
        ["continued_from_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_document_id"),
        "interview_sessions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_interview_round_id"),
        "interview_sessions",
        ["interview_round_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_prep_session_id"),
        "interview_sessions",
        ["prep_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_project_id"), "interview_sessions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_stakeholder_profile_id"),
        "interview_sessions",
        ["stakeholder_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_status"), "interview_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_user_id"), "interview_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "question_cards",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("interview_theme_id", sa.String(), nullable=True),
        sa.Column("focus_text", sa.Text(), nullable=True),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(), nullable=False),
        sa.Column("importance", sa.String(), nullable=False),
        sa.Column("coverage_rule", sa.JSON(), nullable=False),
        sa.Column("suggested_followup", sa.Text(), nullable=True),
        sa.Column("expected_answer_elements", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("brd_mapping", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("estimated_seconds", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("ui", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("target_roles", sa.JSON(), nullable=True),
        sa.Column("not_recommended_roles", sa.JSON(), nullable=True),
        sa.Column("expertise_required", sa.JSON(), nullable=True),
        sa.Column("question_intent", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interview_theme_id"],
            ["interview_themes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_cards_document_id"), "question_cards", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_cards_interview_theme_id"),
        "question_cards",
        ["interview_theme_id"],
        unique=False,
    )
    op.create_index(op.f("ix_question_cards_status"), "question_cards", ["status"], unique=False)
    op.create_table(
        "question_card_slots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question_card_id", sa.String(), nullable=False),
        sa.Column("slot_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_card_id"], ["question_cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["stakeholder_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_card_id", "slot_id", name="uq_question_card_slot"),
    )
    op.create_index(
        op.f("ix_question_card_slots_question_card_id"),
        "question_card_slots",
        ["question_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_card_slots_slot_id"),
        "question_card_slots",
        ["slot_id"],
        unique=False,
    )
    op.create_table(
        "ai_usage_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interview_session_id", sa.String(), nullable=True),
        sa.Column("document_id", sa.String(), nullable=True),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("audio_seconds", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("pricing", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interview_session_id"],
            ["interview_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "operation", "source_id", name="uq_ai_usage_event_document_source"
        ),
        sa.UniqueConstraint(
            "interview_session_id", "operation", "source_id", name="uq_ai_usage_event_source"
        ),
    )
    op.create_index(
        op.f("ix_ai_usage_events_document_id"), "ai_usage_events", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_usage_events_interview_session_id"),
        "ai_usage_events",
        ["interview_session_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ai_usage_events_model"), "ai_usage_events", ["model"], unique=False)
    op.create_index(
        op.f("ix_ai_usage_events_operation"), "ai_usage_events", ["operation"], unique=False
    )
    op.create_index(
        op.f("ix_ai_usage_events_source_id"), "ai_usage_events", ["source_id"], unique=False
    )
    op.create_table(
        "card_coverage_evaluations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("covered_element_ids", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("missing_element_ids", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluation_seq", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["question_cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_card_coverage_evaluations_card_id"),
        "card_coverage_evaluations",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        "ix_card_coverage_evaluations_session_card",
        "card_coverage_evaluations",
        ["session_id", "card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_card_coverage_evaluations_session_id"),
        "card_coverage_evaluations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "interview_briefs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("stakeholder_profile_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("interview_objective", sa.Text(), nullable=False),
        sa.Column("recommended_topics", sa.JSON(), nullable=False),
        sa.Column("excluded_topics", sa.JSON(), nullable=False),
        sa.Column("suggested_questions", sa.JSON(), nullable=False),
        sa.Column("follow_up_from_prior_interviews", sa.JSON(), nullable=False),
        sa.Column("applicable_card_ids", sa.JSON(), nullable=False),
        sa.Column("not_applicable_cards", sa.JSON(), nullable=False),
        sa.Column("time_estimate_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["stakeholder_profile_id"], ["stakeholder_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_interview_briefs_project_id"), "interview_briefs", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_briefs_session_id"), "interview_briefs", ["session_id"], unique=False
    )
    op.create_table(
        "interview_card_states",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("question_card_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "activation_score", sa.Numeric(precision=4, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "completion_score", sa.Numeric(precision=4, scale=3), server_default="0", nullable=False
        ),
        sa.Column("completion_source", sa.String(), nullable=True),
        sa.Column("manual_note", sa.Text(), nullable=True),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.Column("evidence_transcript", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_card_id"],
            ["question_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_card_states_question_card_id"),
        "interview_card_states",
        ["question_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_card_states_session_id"),
        "interview_card_states",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "interview_insight_memos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("stakeholder_profile_id", sa.String(), nullable=True),
        sa.Column("interview_series_id", sa.String(), nullable=True),
        sa.Column("interview_round_id", sa.String(), nullable=True),
        sa.Column("interview_date", sa.DateTime(), nullable=True),
        sa.Column("interview_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("topics_covered", sa.JSON(), nullable=False),
        sa.Column("stakeholder_summary", sa.JSON(), nullable=True),
        sa.Column("question_summaries", sa.JSON(), nullable=False),
        sa.Column("pain_points", sa.JSON(), nullable=False),
        sa.Column("requirement_candidates", sa.JSON(), nullable=False),
        sa.Column("constraints_and_assumptions", sa.JSON(), nullable=False),
        sa.Column("process_descriptions", sa.JSON(), nullable=False),
        sa.Column("unresolved_questions", sa.JSON(), nullable=False),
        sa.Column("next_interview_suggestions", sa.JSON(), nullable=False),
        sa.Column("source_distinction", sa.JSON(), nullable=True),
        sa.Column("markdown_content", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_round_id"], ["interview_rounds.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["interview_series_id"], ["interview_series.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["stakeholder_profile_id"], ["stakeholder_profiles.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        "ix_insight_memos_project_id", "interview_insight_memos", ["project_id"], unique=False
    )
    op.create_index(
        "ix_insight_memos_session_id", "interview_insight_memos", ["session_id"], unique=False
    )
    op.create_index(
        "ix_insight_memos_stakeholder_id",
        "interview_insight_memos",
        ["stakeholder_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_insight_memos_interview_round_id"),
        "interview_insight_memos",
        ["interview_round_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_insight_memos_interview_series_id"),
        "interview_insight_memos",
        ["interview_series_id"],
        unique=False,
    )
    op.create_table(
        "live_utterances",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("realtime_event_id", sa.String(), nullable=True),
        sa.Column("theme_id", sa.String(), nullable=True),
        sa.Column("asked_card_ids", sa.JSON(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theme_id"], ["interview_themes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_live_utterances_session_id"), "live_utterances", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_live_utterances_theme_id"), "live_utterances", ["theme_id"], unique=False
    )
    op.create_table(
        "card_criterion_evidence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("criterion_id", sa.String(), nullable=False),
        sa.Column("utterance_id", sa.String(), nullable=True),
        sa.Column("evaluation_turn_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column("normalized_value", sa.Text(), nullable=True),
        sa.Column("evaluator_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("evaluation_seq", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["question_cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["utterance_id"], ["live_utterances.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_card_criterion_evidence_card_id"),
        "card_criterion_evidence",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_card_criterion_evidence_criterion_id"),
        "card_criterion_evidence",
        ["criterion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_card_criterion_evidence_session_id"),
        "card_criterion_evidence",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_cce_session_card", "card_criterion_evidence", ["session_id", "card_id"], unique=False
    )
    op.create_index(
        "ix_cce_session_card_criterion",
        "card_criterion_evidence",
        ["session_id", "card_id", "criterion_id"],
        unique=False,
    )
    op.create_table(
        "card_evidence_slots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.Column("slot_id", sa.String(), nullable=False),
        sa.Column("relevance", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["card_criterion_evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["stakeholder_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evidence_id", "slot_id", name="uq_card_evidence_slot"),
    )
    op.create_index(
        op.f("ix_card_evidence_slots_evidence_id"),
        "card_evidence_slots",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_card_evidence_slots_slot_id"),
        "card_evidence_slots",
        ["slot_id"],
        unique=False,
    )
    op.create_table(
        "interview_round_aggregates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("latest_memo_id", sa.String(), nullable=True),
        sa.Column("source_session_ids", sa.JSON(), nullable=False),
        sa.Column("coverage_snapshot", sa.JSON(), nullable=False),
        sa.Column("evidence_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["latest_memo_id"], ["interview_insight_memos.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["round_id"], ["interview_rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("latest_memo_id", name="uq_interview_round_aggregates_latest_memo_id"),
        sa.UniqueConstraint("round_id", name="uq_interview_round_aggregates_round_id"),
    )
    op.create_index(
        op.f("ix_interview_round_aggregates_latest_memo_id"),
        "interview_round_aggregates",
        ["latest_memo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_round_aggregates_round_id"),
        "interview_round_aggregates",
        ["round_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_round_aggregates_status"),
        "interview_round_aggregates",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_interview_round_aggregates_status"), table_name="interview_round_aggregates"
    )
    op.drop_index(
        op.f("ix_interview_round_aggregates_round_id"), table_name="interview_round_aggregates"
    )
    op.drop_index(
        op.f("ix_interview_round_aggregates_latest_memo_id"),
        table_name="interview_round_aggregates",
    )
    op.drop_table("interview_round_aggregates")
    op.drop_index(op.f("ix_card_evidence_slots_slot_id"), table_name="card_evidence_slots")
    op.drop_index(op.f("ix_card_evidence_slots_evidence_id"), table_name="card_evidence_slots")
    op.drop_table("card_evidence_slots")
    op.drop_index("ix_cce_session_card_criterion", table_name="card_criterion_evidence")
    op.drop_index("ix_cce_session_card", table_name="card_criterion_evidence")
    op.drop_index(
        op.f("ix_card_criterion_evidence_session_id"), table_name="card_criterion_evidence"
    )
    op.drop_index(
        op.f("ix_card_criterion_evidence_criterion_id"), table_name="card_criterion_evidence"
    )
    op.drop_index(op.f("ix_card_criterion_evidence_card_id"), table_name="card_criterion_evidence")
    op.drop_table("card_criterion_evidence")
    op.drop_index(op.f("ix_live_utterances_theme_id"), table_name="live_utterances")
    op.drop_index(op.f("ix_live_utterances_session_id"), table_name="live_utterances")
    op.drop_table("live_utterances")
    op.drop_index(
        op.f("ix_interview_insight_memos_interview_series_id"), table_name="interview_insight_memos"
    )
    op.drop_index(
        op.f("ix_interview_insight_memos_interview_round_id"), table_name="interview_insight_memos"
    )
    op.drop_index("ix_insight_memos_stakeholder_id", table_name="interview_insight_memos")
    op.drop_index("ix_insight_memos_session_id", table_name="interview_insight_memos")
    op.drop_index("ix_insight_memos_project_id", table_name="interview_insight_memos")
    op.drop_table("interview_insight_memos")
    op.drop_index(op.f("ix_interview_card_states_session_id"), table_name="interview_card_states")
    op.drop_index(
        op.f("ix_interview_card_states_question_card_id"), table_name="interview_card_states"
    )
    op.drop_table("interview_card_states")
    op.drop_index(op.f("ix_interview_briefs_session_id"), table_name="interview_briefs")
    op.drop_index(op.f("ix_interview_briefs_project_id"), table_name="interview_briefs")
    op.drop_table("interview_briefs")
    op.drop_index(
        op.f("ix_card_coverage_evaluations_session_id"), table_name="card_coverage_evaluations"
    )
    op.drop_index(
        "ix_card_coverage_evaluations_session_card", table_name="card_coverage_evaluations"
    )
    op.drop_index(
        op.f("ix_card_coverage_evaluations_card_id"), table_name="card_coverage_evaluations"
    )
    op.drop_table("card_coverage_evaluations")
    op.drop_index(op.f("ix_ai_usage_events_source_id"), table_name="ai_usage_events")
    op.drop_index(op.f("ix_ai_usage_events_operation"), table_name="ai_usage_events")
    op.drop_index(op.f("ix_ai_usage_events_model"), table_name="ai_usage_events")
    op.drop_index(op.f("ix_ai_usage_events_interview_session_id"), table_name="ai_usage_events")
    op.drop_index(op.f("ix_ai_usage_events_document_id"), table_name="ai_usage_events")
    op.drop_table("ai_usage_events")
    op.drop_index(op.f("ix_question_card_slots_slot_id"), table_name="question_card_slots")
    op.drop_index(
        op.f("ix_question_card_slots_question_card_id"), table_name="question_card_slots"
    )
    op.drop_table("question_card_slots")
    op.drop_index(op.f("ix_question_cards_status"), table_name="question_cards")
    op.drop_index(op.f("ix_question_cards_interview_theme_id"), table_name="question_cards")
    op.drop_index(op.f("ix_question_cards_document_id"), table_name="question_cards")
    op.drop_table("question_cards")
    op.drop_index(op.f("ix_interview_sessions_user_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_status"), table_name="interview_sessions")
    op.drop_index(
        op.f("ix_interview_sessions_stakeholder_profile_id"), table_name="interview_sessions"
    )
    op.drop_index(op.f("ix_interview_sessions_project_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_prep_session_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_interview_round_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_document_id"), table_name="interview_sessions")
    op.drop_index(
        op.f("ix_interview_sessions_continued_from_session_id"), table_name="interview_sessions"
    )
    op.drop_table("interview_sessions")
    op.drop_index(op.f("ix_prep_sessions_user_id"), table_name="prep_sessions")
    op.drop_index(op.f("ix_prep_sessions_status"), table_name="prep_sessions")
    op.drop_index(op.f("ix_prep_sessions_document_id"), table_name="prep_sessions")
    op.drop_table("prep_sessions")
    op.drop_index(op.f("ix_interview_themes_document_id"), table_name="interview_themes")
    op.drop_table("interview_themes")
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_stakeholder_profile_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_project_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_is_frozen"), table_name="documents")
    op.drop_index(op.f("ix_documents_interview_round_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_interview_round_slots_slot_id"), table_name="interview_round_slots")
    op.drop_index(op.f("ix_interview_round_slots_round_id"), table_name="interview_round_slots")
    op.drop_table("interview_round_slots")
    op.drop_index(op.f("ix_interview_rounds_status"), table_name="interview_rounds")
    op.drop_index(op.f("ix_interview_rounds_series_id"), table_name="interview_rounds")
    op.drop_index(op.f("ix_interview_rounds_guide_document_id"), table_name="interview_rounds")
    op.drop_table("interview_rounds")
    op.drop_index(op.f("ix_interview_series_status"), table_name="interview_series")
    op.drop_index(op.f("ix_interview_series_stakeholder_profile_id"), table_name="interview_series")
    op.drop_index(op.f("ix_interview_series_project_id"), table_name="interview_series")
    op.drop_table("interview_series")
    op.drop_index(op.f("ix_stakeholder_profile_slots_slot_id"), table_name="stakeholder_profile_slots")
    op.drop_index(
        op.f("ix_stakeholder_profile_slots_project_id"), table_name="stakeholder_profile_slots"
    )
    op.drop_index(
        op.f("ix_stakeholder_profile_slots_profile_id"), table_name="stakeholder_profile_slots"
    )
    op.drop_table("stakeholder_profile_slots")
    op.drop_index(op.f("ix_stakeholder_profiles_project_id"), table_name="stakeholder_profiles")
    op.drop_table("stakeholder_profiles")
    op.drop_index(op.f("ix_stakeholder_slots_project_id"), table_name="stakeholder_slots")
    op.drop_table("stakeholder_slots")
    op.drop_index("ix_evidence_matrices_project_id", table_name="requirement_evidence_matrices")
    op.drop_table("requirement_evidence_matrices")
    op.drop_index(op.f("ix_brd_readiness_reports_project_id"), table_name="brd_readiness_reports")
    op.drop_table("brd_readiness_reports")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
