"""initial_schema

Revision ID: 0edc97eda1b4
Revises: 
Create Date: 2026-05-22 16:19:28.111765

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0edc97eda1b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
